window.ENVISTA_DATA = {
  participant: { id: 'u-lucas', name: 'Lucas Ferreira', handle: '@lucasfer', role: 'participant', school: 'SESI SENAI', city: 'Rio de Janeiro, RJ', bio: 'Desenvolvedor e competidor apaixonado por tecnologia de impacto.', skills: ['Programação', 'Robótica', 'IoT'] },
  investor: { id: 'u-marina', name: 'Marina Alves', handle: '@marinaalves', role: 'investor', organization: 'Horizonte Ventures', title: 'Analista de inovação', city: 'São Paulo, SP', bio: 'Conecto tecnologia, educação e impacto social.', skills: ['EdTech', 'Sustentabilidade', 'IA', 'Impacto social'] },
  teams: [
    { id: 'atlas', name: 'Atlas', category: 'IoT + sustentabilidade', role: 'Desenvolvedor', members: 6, projects: 2, color: 'blue', description: 'Tecnologia para tornar escolas mais eficientes.', school: 'SESI SENAI', city: 'Rio de Janeiro, RJ' },
    { id: 'orion', name: 'Orion', category: 'Robótica', role: 'Líder de Projeto', members: 5, projects: 1, color: 'orange', description: 'Robótica acessível para desafios reais.', school: 'Instituto Federal', city: 'Niterói, RJ' },
    { id: 'nova', name: 'Nova', category: 'Educação + IA', role: 'Mentor', members: 8, projects: 3, color: 'purple', description: 'Experiências de aprendizagem mais inclusivas.', school: 'Colégio Estadual Horizonte', city: 'Duque de Caxias, RJ' },
    { id: 'lumina', name: 'Lumina', category: 'Tecnologia assistiva', role: 'Colaborador', members: 4, projects: 1, color: 'teal', description: 'Acessibilidade construída com quem precisa dela.', school: 'SENAI', city: 'São Paulo, SP' }
  ],
  projects: [
    { id: 'aqua', slug: 'aqua', name: 'Aqua', author: 'Atlas', authorType: 'team', text: 'Monitoramento inteligente para ajudar escolas a reduzir desperdício de água.', problem: 'Escolas demoram a identificar vazamentos e desperdícios.', solution: 'Sensores conectados mostram consumo e alertas em um painel simples.', tag: 'Sustentabilidade', stage: 'Protótipo', tags: ['Arduino', 'IoT', 'Sensores'], likes: 0, progress: 72, color: 'project-blue', updated: 'Atualizado há 2 dias', saved: true },
    { id: 'visionaid', slug: 'visionaid', name: 'VisionAid', author: 'Lumina', authorType: 'team', text: 'Visão computacional para auxiliar pessoas com deficiência visual.', problem: 'Obstáculos urbanos reduzem autonomia e segurança.', solution: 'Uma câmera portátil identifica obstáculos e fornece alertas sonoros.', tag: 'Acessibilidade', stage: 'MVP', tags: ['IA', 'Visão computacional'], likes: 0, progress: 84, color: 'project-green', updated: 'Atualizado ontem', saved: false },
    { id: 'reciclo', slug: 'reciclo', name: 'ReCiclo', author: 'Equipe Nova', authorType: 'team', text: 'Jornada educativa para incentivar coleta seletiva dentro de escolas.', problem: 'A coleta seletiva escolar tem baixa adesão.', solution: 'Missões por turma combinam educação ambiental e acompanhamento.', tag: 'Educação', stage: 'Validação', tags: ['Educação', 'Sustentabilidade'], likes: 0, progress: 48, color: 'project-green', updated: 'Atualizado há 5 dias', saved: false },
    { id: 'edumatch', slug: 'edumatch', name: 'EduMatch', author: 'Lucas Ferreira', authorType: 'user', text: 'Conecta estudantes a oportunidades educacionais alinhadas aos seus interesses.', problem: 'Oportunidades relevantes estão dispersas e chegam a poucos alunos.', solution: 'Um perfil de interesses recomenda bolsas, cursos e competições.', tag: 'EdTech', stage: 'Protótipo', tags: ['Educação', 'Recomendação'], likes: 0, progress: 61, color: 'project-purple', updated: 'Atualizado há 1 semana', saved: true }
  ],
  people: ['Ana Souza', 'Beatriz Lima', 'Rafael Costa', 'Pedro Martins', 'Júlia Nascimento', 'Caio Ribeiro', 'Sofia Mendes', 'Gabriel Rocha', 'Larissa Freitas', 'Mateus Carvalho'],
  courses: ['Da ideia ao projeto', 'Validação na prática', 'Como apresentar seu projeto', 'Introdução à inovação', 'Preparação para competições'],
  competitions: ['Envista Challenge 2026', 'Olimpíada Brasileira de Tecnologia', 'Desafio Jovens Inovadores']
};
